version: 0.2
env:
  variables:
    LOGIN: "f0a242e54f7a8a9dc329707ba5e4db09460d49bc"
    HOST: "https://sonarcloud.io"
    Organization: "vaishnaviisasre_springboot"
    Project: "vaishnaviisasre"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Install phase ..."
  pre_build:
    commands:
      - echo "Pre build phase ..."
      - yum update -y
      - yum install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - echo "Current path is >>> $PWD"
      - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip
      - ls $PWD
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
      - curl -sL https://rpm.nodesource.com/setup_14.x | bash -
      - yum install -y nodejs
  build:
    commands:
      - echo "Build phase ..."
      - echo "Login value: $LOGIN"
      - echo "Host Name: $HOST"
      - echo "Organization Name: $Organization"
      - echo "Project Name: $Project"
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then
            echo "Build failed due to SonarCloud error."
            exit 1
          fi
        fi
  post_build:
    commands:
      - echo "Post build phase ..."
